/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Players */
        get: operations["players_api_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player */
        get: operations["player_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contract */
        get: operations["contract_api_players__player_id__contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Seasons */
        get: operations["player_seasons_api_players__player_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Stats */
        get: operations["player_stats_api_players__player_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hockey Value */
        get: operations["hockey_value_api_players__player_id__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/value/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Value History */
        get: operations["value_history_api_players__player_id__value_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Players */
        get: operations["compare_players_api_players_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings/hockey-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hockey Value Leaders */
        get: operations["hockey_value_leaders_api_rankings_hockey_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasons */
        get: operations["seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams */
        get: operations["teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team */
        get: operations["team_api_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/cap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Cap */
        get: operations["team_cap_api_teams__team_id__cap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Contracts */
        get: operations["team_contracts_api_teams__team_id__contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roster */
        get: operations["roster_api_teams__team_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvancedSkaterStats */
        AdvancedSkaterStats: {
            /** Expectedgoalsper60 */
            expectedGoalsPer60: number | null;
            /** Gamescore */
            gameScore: number | null;
            /** Gamescoreper60 */
            gameScorePer60: number | null;
            /** Giveaways */
            giveaways: number | null;
            /** Icetimeseconds */
            iceTimeSeconds: number | null;
            /** Individualexpectedgoals */
            individualExpectedGoals: number | null;
            /** Oniceexpectedgoalspercentage */
            onIceExpectedGoalsPercentage: number | null;
            /** Penalties */
            penalties: number | null;
            /** Penaltiesdrawn */
            penaltiesDrawn: number | null;
            /** Shifts */
            shifts: number | null;
            /** Shotsblocked */
            shotsBlocked: number | null;
            /** Situation */
            situation: string;
            /** Takeaways */
            takeaways: number | null;
        };
        /** AvailableSeason */
        AvailableSeason: {
            /** Endyear */
            endYear: number;
            /** Label */
            label: string;
            /** Salarycapcents */
            salaryCapCents: number | null;
            /** Startyear */
            startYear: number;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Players */
            players: components["schemas"]["CompareRow"][];
            /** Season */
            season: number;
        };
        /** CompareRow */
        CompareRow: {
            contract: components["schemas"]["Contract"] | null;
            player: components["schemas"]["PlayerIdentity"];
            stats: components["schemas"]["PlayerStats"];
            value: components["schemas"]["HockeyValue"] | null;
        };
        /** Contract */
        Contract: {
            /** Averagevaluecents */
            averageValueCents: number | null;
            /** Contracttype */
            contractType: string | null;
            /** Endseason */
            endSeason: number;
            /** Expirystatus */
            expiryStatus: ("RFA" | "UFA") | null;
            /** Id */
            id: number;
            /** Isentrylevel */
            isEntryLevel: boolean;
            /** Playerid */
            playerId: number;
            /** Seasons */
            seasons: components["schemas"]["ContractSeason"][];
            /** Signedon */
            signedOn: string | null;
            signingTeam: components["schemas"]["TeamSummary"] | null;
            /** Startseason */
            startSeason: number;
            /** Termyears */
            termYears: number;
            /** Totalvaluecents */
            totalValueCents: number | null;
        };
        /** ContractSeason */
        ContractSeason: {
            /** Basesalarycents */
            baseSalaryCents: number | null;
            /** Caphitcents */
            capHitCents: number;
            /** Cappercentage */
            capPercentage: number | null;
            /** Isslide */
            isSlide: boolean;
            owningTeam: components["schemas"]["TeamSummary"] | null;
            /** Performancebonuscents */
            performanceBonusCents: number | null;
            /** Season */
            season: number;
            /** Signingbonuscents */
            signingBonusCents: number | null;
            /** Totalcashcents */
            totalCashCents: number | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: string[];
            } | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** GoalieStats */
        GoalieStats: {
            /** Expectedgoalsagainst */
            expectedGoalsAgainst: number | null;
            /** Gamesplayed */
            gamesPlayed: number | null;
            /** Goalsagainstaverage */
            goalsAgainstAverage: number | null;
            /** Goalssavedaboveexpected */
            goalsSavedAboveExpected: number | null;
            /** Losses */
            losses: number | null;
            /** Overtimelosses */
            overtimeLosses: number | null;
            /** Savepercentage */
            savePercentage: number | null;
            /** Saves */
            saves: number | null;
            /** Shotsagainst */
            shotsAgainst: number | null;
            /** Shutouts */
            shutouts: number | null;
            /** Timeoniceseconds */
            timeOnIceSeconds: number | null;
            /** Wins */
            wins: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HockeyValue */
        HockeyValue: {
            /** Gamescoreper60Abovereplacement */
            gameScorePer60AboveReplacement: number | null;
            /** Hockeyvalue */
            hockeyValue: number | null;
            /** Modelversion */
            modelVersion: string | null;
            /** Playerid */
            playerId: number;
            /** Projectednextseasonhockeyvalue */
            projectedNextSeasonHockeyValue: number | null;
            /** Season */
            season: number;
            /** Toihours */
            toiHours: number | null;
        };
        /** HockeyValueHistoryPoint */
        HockeyValueHistoryPoint: {
            /** Hockeyvalue */
            hockeyValue: number | null;
            /** Season */
            season: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeagueOverview */
        LeagueOverview: {
            /** Averagehockeyvalue */
            averageHockeyValue: number | null;
            /** Gamesplayed */
            gamesPlayed: number;
            /** Goals */
            goals: number;
            /** Players */
            players: number;
        };
        /** OverviewLeaders */
        OverviewLeaders: {
            /** Gamescoreper60 */
            gameScorePer60: components["schemas"]["PlayerSummary"][];
            /** Goals */
            goals: components["schemas"]["PlayerSummary"][];
            /** Hockeyvalue */
            hockeyValue: components["schemas"]["PlayerSummary"][];
            /** Points */
            points: components["schemas"]["PlayerSummary"][];
        };
        /** OverviewResponse */
        OverviewResponse: {
            leaders: components["schemas"]["OverviewLeaders"];
            league: components["schemas"]["LeagueOverview"];
            /** Season */
            season: number;
        };
        /** PaginatedPlayers */
        PaginatedPlayers: {
            /** Data */
            data: components["schemas"]["PlayerSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalitems */
            totalItems: number;
            /** Totalpages */
            totalPages: number;
        };
        /** PlayerIdentity */
        PlayerIdentity: {
            /** Active */
            active: boolean;
            /** Age */
            age: number | null;
            /** Birthdate */
            birthDate: string | null;
            /** Firstname */
            firstName: string;
            /** Fullname */
            fullName: string;
            /** Id */
            id: number;
            /** Lastname */
            lastName: string;
            /** Nationality */
            nationality: string | null;
            primaryPosition: components["schemas"]["Position"] | null;
            rosterStatus: components["schemas"]["RosterStatus"];
            /** Shootscatches */
            shootsCatches: ("L" | "R") | null;
            team: components["schemas"]["TeamSummary"] | null;
        };
        /** PlayerStats */
        PlayerStats: {
            advanced: components["schemas"]["AdvancedSkaterStats"] | null;
            goalie: components["schemas"]["GoalieStats"] | null;
            /** Playerid */
            playerId: number;
            /** Season */
            season: number;
            team: components["schemas"]["TeamSummary"] | null;
            traditional: components["schemas"]["TraditionalSkaterStats"] | null;
        };
        /** PlayerSummary */
        PlayerSummary: {
            /** Active */
            active: boolean;
            /** Age */
            age: number | null;
            /** Assists */
            assists: number | null;
            /** Birthdate */
            birthDate: string | null;
            /** Caphitcents */
            capHitCents: number | null;
            /** Firstname */
            firstName: string;
            /** Fullname */
            fullName: string;
            /** Gamescore */
            gameScore: number | null;
            /** Gamescoreper60 */
            gameScorePer60: number | null;
            /** Gamesplayed */
            gamesPlayed: number | null;
            /** Goals */
            goals: number | null;
            /** Hockeyvalue */
            hockeyValue: number | null;
            /** Id */
            id: number;
            /** Lastname */
            lastName: string;
            /** Nationality */
            nationality: string | null;
            /** Points */
            points: number | null;
            primaryPosition: components["schemas"]["Position"] | null;
            /** Projectednextseasonhockeyvalue */
            projectedNextSeasonHockeyValue: number | null;
            rosterStatus: components["schemas"]["RosterStatus"];
            /** Season */
            season: number;
            /** Shootscatches */
            shootsCatches: ("L" | "R") | null;
            team: components["schemas"]["TeamSummary"] | null;
            /** Toiseconds */
            toiSeconds: number | null;
        };
        /**
         * Position
         * @enum {string}
         */
        Position: "C" | "LW" | "RW" | "D" | "G" | "F";
        /**
         * RosterStatus
         * @enum {string}
         */
        RosterStatus: "ACTIVE" | "MINORS" | "LTIR" | "UNKNOWN";
        /** SearchResponse */
        SearchResponse: {
            /** Players */
            players: components["schemas"]["PlayerIdentity"][];
            /** Teams */
            teams: components["schemas"]["TeamSummary"][];
        };
        /** SeasonHistoryRow */
        SeasonHistoryRow: {
            /** Assists */
            assists: number | null;
            /** Gamescoreper60 */
            gameScorePer60: number | null;
            /** Gamesplayed */
            gamesPlayed: number | null;
            /** Goals */
            goals: number | null;
            /** Hockeyvalue */
            hockeyValue: number | null;
            /** Points */
            points: number | null;
            /** Season */
            season: number;
            team: components["schemas"]["TeamSummary"] | null;
        };
        /** SeasonInfo */
        SeasonInfo: {
            /** Availableseasons */
            availableSeasons: components["schemas"]["AvailableSeason"][];
            /** Currentseason */
            currentSeason: number;
        };
        /** Team */
        Team: {
            /** Abbreviation */
            abbreviation: string;
            /** Active */
            active: boolean;
            /** City */
            city: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Nhlteamid */
            nhlTeamId: number | null;
            /** Rostercounts */
            rosterCounts: {
                [key: string]: number;
            };
        };
        /** TeamCap */
        TeamCap: {
            /** Activerostercapcents */
            activeRosterCapCents: number;
            /**
             * Calculationstatus
             * @enum {string}
             */
            calculationStatus: "ESTIMATE" | "AUTHORITATIVE";
            /** Capspacecents */
            capSpaceCents: number | null;
            /** Ltircapcents */
            ltirCapCents: number;
            /** Minorscapcents */
            minorsCapCents: number;
            /** Salarycapcents */
            salaryCapCents: number | null;
            /** Season */
            season: number;
            /** Teamid */
            teamId: number;
            /** Totalcommitmentscents */
            totalCommitmentsCents: number;
        };
        /** TeamContractRow */
        TeamContractRow: {
            contract: components["schemas"]["Contract"];
            player: components["schemas"]["PlayerIdentity"];
            season: components["schemas"]["ContractSeason"];
        };
        /** TeamContractsResponse */
        TeamContractsResponse: {
            /** Contracts */
            contracts: components["schemas"]["TeamContractRow"][];
            /** Season */
            season: number;
            team: components["schemas"]["TeamSummary"];
        };
        /** TeamRosterResponse */
        TeamRosterResponse: {
            /** Players */
            players: components["schemas"]["PlayerSummary"][];
            /** Season */
            season: number;
            status: components["schemas"]["RosterStatus"] | null;
            team: components["schemas"]["TeamSummary"];
        };
        /** TeamSummary */
        TeamSummary: {
            /** Abbreviation */
            abbreviation: string;
            /** Active */
            active: boolean;
            /** City */
            city: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Nhlteamid */
            nhlTeamId: number | null;
        };
        /** TraditionalSkaterStats */
        TraditionalSkaterStats: {
            /** Assists */
            assists: number | null;
            /** Gamesplayed */
            gamesPlayed: number | null;
            /** Goals */
            goals: number | null;
            /** Penaltyminutes */
            penaltyMinutes: number | null;
            /** Plusminus */
            plusMinus: number | null;
            /** Points */
            points: number | null;
            /** Powerplaygoals */
            powerPlayGoals: number | null;
            /** Powerplaypoints */
            powerPlayPoints: number | null;
            /** Shootingpercentage */
            shootingPercentage: number | null;
            /** Shorthandedgoals */
            shortHandedGoals: number | null;
            /** Shots */
            shots: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    players_api_players_get: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                page?: number;
                pageSize?: number;
                position?: components["schemas"]["Position"] | null;
                rosterStatus?: components["schemas"]["RosterStatus"] | null;
                search?: string | null;
                season?: number | null;
                sort?: "name" | "team" | "gamesPlayed" | "goals" | "assists" | "points" | "gameScore" | "gameScorePer60" | "hockeyValue" | "capHitCents";
                team?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlayers"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerIdentity"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    contract_api_players__player_id__contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"] | null;
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_seasons_api_players__player_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonHistoryRow"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    player_stats_api_players__player_id__stats_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStats"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    hockey_value_api_players__player_id__value_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HockeyValue"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    value_history_api_players__player_id__value_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HockeyValueHistoryPoint"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_players_api_players_compare_get: {
        parameters: {
            query: {
                ids: string;
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    hockey_value_leaders_api_rankings_hockey_value_get: {
        parameters: {
            query: {
                limit?: number;
                position?: components["schemas"]["Position"] | null;
                season: number;
                team?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                limit?: number;
                q: string;
                types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonInfo"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSummary"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    team_api_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    team_cap_api_teams__team_id__cap_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamCap"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    team_contracts_api_teams__team_id__contracts_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamContractsResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    roster_api_teams__team_id__roster_get: {
        parameters: {
            query: {
                season: number;
                status?: components["schemas"]["RosterStatus"] | null;
            };
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRosterResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal API error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
