-- TradeValue PostgreSQL schema.
--
-- Design rules:
--   * Player identity, performance, and contracts are independent timelines.
--   * External identifiers are retained so ingestion never relies on names.
--   * Money is stored in cents; percentages are stored as ratios (0.10 = 10%).
--   * Frequently modeled metrics are typed. Source-specific long-tail metrics
--     remain available in JSONB until they earn a stable typed column.

BEGIN;

CREATE TYPE roster_status AS ENUM (
    'ACTIVE',
    'MINORS',
    'LTIR',
    'UNKNOWN'
);

CREATE TABLE data_sources (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(32) NOT NULL UNIQUE,
    display_name    VARCHAR(100) NOT NULL,
    base_url        TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO data_sources (code, display_name, base_url)
VALUES
    ('nhl', 'NHL', 'https://www.nhl.com'),
    ('moneypuck', 'MoneyPuck', 'https://moneypuck.com'),
    ('capwages', 'CapWages', 'https://capwages.com');

CREATE TABLE seasons (
    start_year          SMALLINT PRIMARY KEY,
    end_year            SMALLINT NOT NULL,
    label               VARCHAR(9) NOT NULL UNIQUE,
    regular_start_date  DATE,
    regular_end_date    DATE,
    salary_cap_cents    BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT seasons_consecutive_years
        CHECK (end_year = start_year + 1),
    CONSTRAINT seasons_positive_salary_cap
        CHECK (salary_cap_cents IS NULL OR salary_cap_cents >= 0),
    CONSTRAINT seasons_valid_dates
        CHECK (
            regular_start_date IS NULL
            OR regular_end_date IS NULL
            OR regular_end_date >= regular_start_date
        )
);

-- Salary-cap history currently used by the contract ingestion pipeline.
INSERT INTO seasons (start_year, end_year, label, salary_cap_cents)
VALUES
    (2005, 2006, '2005-06',  3900000000),
    (2006, 2007, '2006-07',  4400000000),
    (2007, 2008, '2007-08',  5030000000),
    (2008, 2009, '2008-09',  5670000000),
    (2009, 2010, '2009-10',  5680000000),
    (2010, 2011, '2010-11',  5940000000),
    (2011, 2012, '2011-12',  6430000000),
    (2012, 2013, '2012-13',  7020000000),
    (2013, 2014, '2013-14',  6430000000),
    (2014, 2015, '2014-15',  6900000000),
    (2015, 2016, '2015-16',  7140000000),
    (2016, 2017, '2016-17',  7300000000),
    (2017, 2018, '2017-18',  7500000000),
    (2018, 2019, '2018-19',  7950000000),
    (2019, 2020, '2019-20',  8150000000),
    (2020, 2021, '2020-21',  8150000000),
    (2021, 2022, '2021-22',  8150000000),
    (2022, 2023, '2022-23',  8250000000),
    (2023, 2024, '2023-24',  8350000000),
    (2024, 2025, '2024-25',  8800000000),
    (2025, 2026, '2025-26',  9550000000),
    (2026, 2027, '2026-27', 10400000000);

CREATE TABLE teams (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhl_team_id         INTEGER UNIQUE,
    nhl_franchise_id    INTEGER,
    abbreviation        VARCHAR(4) NOT NULL UNIQUE,
    name                VARCHAR(120) NOT NULL,
    city                VARCHAR(120),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    birth_date          DATE,
    primary_position    VARCHAR(3),
    shoots_catches      CHAR(1),
    nationality         VARCHAR(3),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    roster_status       roster_status NOT NULL DEFAULT 'UNKNOWN',
    roster_status_updated_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT players_valid_position
        CHECK (
            primary_position IS NULL
            OR primary_position IN ('C', 'LW', 'RW', 'D', 'G', 'F')
        ),
    CONSTRAINT players_valid_handedness
        CHECK (shoots_catches IS NULL OR shoots_catches IN ('L', 'R'))
);

CREATE INDEX players_name_idx
    ON players (LOWER(last_name), LOWER(first_name));

CREATE INDEX players_roster_status_idx
    ON players (roster_status);

COMMENT ON COLUMN players.roster_status IS
    'Roster classification used by cap calculations. UNKNOWN means the free sources did not provide enough evidence.';

CREATE TABLE player_external_ids (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id           BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    source_id           BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    external_id         TEXT NOT NULL,
    source_slug         TEXT,
    source_name         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_external_ids_source_key
        UNIQUE (source_id, external_id)
);

CREATE INDEX player_external_ids_player_idx
    ON player_external_ids (player_id, source_id);

CREATE TABLE ltir_overrides (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id   BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    start_date  DATE NOT NULL,
    end_date    DATE,
    notes       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ltir_overrides_valid_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX ltir_overrides_player_dates_idx
    ON ltir_overrides (player_id, start_date, end_date);

COMMENT ON TABLE ltir_overrides IS
    'Manual LTIR date ranges. Active overrides take precedence over NHL and AHL roster feeds.';

-- TODO(cap-engine): Apply the NHL buried-contract relief calculation to MINORS.
-- TODO(cap-engine): Apply accrued cap-space and LTIR-pool rules to LTIR.

CREATE TABLE player_team_stints (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id           BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    season_start_year   SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    team_id             BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    joined_on           DATE,
    departed_on         DATE,
    roster_status       VARCHAR(32),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_team_stints_valid_dates
        CHECK (departed_on IS NULL OR joined_on IS NULL OR departed_on >= joined_on)
);

CREATE UNIQUE INDEX player_team_stints_identity_idx
    ON player_team_stints (
        player_id,
        season_start_year,
        team_id,
        COALESCE(joined_on, DATE '0001-01-01')
    );

CREATE TABLE contracts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id               BIGINT NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    signing_team_id         BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    source_id               BIGINT REFERENCES data_sources(id) ON DELETE RESTRICT,
    external_id             TEXT,
    signed_on               DATE,
    start_season            SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    end_season              SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    term_years              SMALLINT NOT NULL,
    contract_type           VARCHAR(32),
    expiry_status           VARCHAR(8),
    total_value_cents       BIGINT,
    average_value_cents     BIGINT,
    is_entry_level          BOOLEAN NOT NULL DEFAULT FALSE,
    source_payload          JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contracts_valid_seasons CHECK (end_season >= start_season),
    CONSTRAINT contracts_positive_term CHECK (term_years > 0),
    CONSTRAINT contracts_valid_expiry_status
        CHECK (expiry_status IS NULL OR expiry_status IN ('RFA', 'UFA')),
    CONSTRAINT contracts_nonnegative_value
        CHECK (total_value_cents IS NULL OR total_value_cents >= 0),
    CONSTRAINT contracts_nonnegative_average
        CHECK (average_value_cents IS NULL OR average_value_cents >= 0)
);

CREATE UNIQUE INDEX contracts_source_external_id_idx
    ON contracts (source_id, external_id)
    WHERE source_id IS NOT NULL AND external_id IS NOT NULL;

CREATE INDEX contracts_player_seasons_idx
    ON contracts (player_id, start_season, end_season);

CREATE TABLE contract_seasons (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id                 BIGINT NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    season_start_year           SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    owning_team_id              BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    base_salary_cents           BIGINT,
    signing_bonus_cents         BIGINT,
    performance_bonus_cents     BIGINT,
    total_cash_cents            BIGINT,
    cap_hit_cents               BIGINT NOT NULL,
    cap_percentage              NUMERIC(9, 8),
    is_slide                    BOOLEAN NOT NULL DEFAULT FALSE,
    clauses                     JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contract_seasons_contract_year_key
        UNIQUE (contract_id, season_start_year),
    CONSTRAINT contract_seasons_nonnegative_money
        CHECK (
            (base_salary_cents IS NULL OR base_salary_cents >= 0)
            AND (signing_bonus_cents IS NULL OR signing_bonus_cents >= 0)
            AND (performance_bonus_cents IS NULL OR performance_bonus_cents >= 0)
            AND (total_cash_cents IS NULL OR total_cash_cents >= 0)
            AND cap_hit_cents >= 0
        ),
    CONSTRAINT contract_seasons_nonnegative_cap_percentage
        CHECK (cap_percentage IS NULL OR cap_percentage >= 0)
);

CREATE INDEX contract_seasons_season_idx
    ON contract_seasons (season_start_year, contract_id);

CREATE TABLE games (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhl_game_id         BIGINT NOT NULL UNIQUE,
    season_start_year   SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    game_type           SMALLINT NOT NULL,
    game_date           DATE NOT NULL,
    start_time_utc      TIMESTAMPTZ,
    away_team_id        BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    home_team_id        BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    venue               VARCHAR(200),
    game_state          VARCHAR(32),
    away_score          SMALLINT,
    home_score          SMALLINT,
    last_synced_at      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT games_valid_game_type CHECK (game_type IN (1, 2, 3)),
    CONSTRAINT games_distinct_teams CHECK (away_team_id <> home_team_id),
    CONSTRAINT games_nonnegative_scores
        CHECK (
            (away_score IS NULL OR away_score >= 0)
            AND (home_score IS NULL OR home_score >= 0)
        )
);

CREATE INDEX games_schedule_idx
    ON games (season_start_year, game_type, start_time_utc);

CREATE TABLE ingestion_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id           BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    job_name            VARCHAR(120) NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'running',
    started_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at         TIMESTAMPTZ,
    records_read        INTEGER NOT NULL DEFAULT 0,
    records_created     INTEGER NOT NULL DEFAULT 0,
    records_updated     INTEGER NOT NULL DEFAULT 0,
    records_skipped     INTEGER NOT NULL DEFAULT 0,
    error_message       TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT ingestion_runs_valid_status
        CHECK (status IN ('running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT ingestion_runs_nonnegative_counts
        CHECK (
            records_read >= 0
            AND records_created >= 0
            AND records_updated >= 0
            AND records_skipped >= 0
        )
);

CREATE INDEX ingestion_runs_recent_idx
    ON ingestion_runs (job_name, started_at DESC);

CREATE TABLE source_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id    BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    source_id           BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    entity_type         VARCHAR(64) NOT NULL,
    external_key        TEXT NOT NULL,
    payload_hash        VARCHAR(128) NOT NULL,
    payload             JSONB NOT NULL,
    fetched_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT source_records_version_key
        UNIQUE (source_id, entity_type, external_key, payload_hash)
);

CREATE INDEX source_records_lookup_idx
    ON source_records (source_id, entity_type, external_key, fetched_at DESC);

CREATE TABLE skater_season_stats (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id               BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    season_start_year       SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    team_id                 BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    stat_scope              VARCHAR(8) NOT NULL DEFAULT 'TEAM',
    game_type               SMALLINT NOT NULL,
    source_id               BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    ingestion_run_id        BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    games_played            SMALLINT,
    goals                   SMALLINT,
    assists                 SMALLINT,
    points                  SMALLINT,
    plus_minus              SMALLINT,
    penalty_minutes         SMALLINT,
    power_play_goals        SMALLINT,
    power_play_points       SMALLINT,
    short_handed_goals      SMALLINT,
    shots                   SMALLINT,
    shooting_percentage     DOUBLE PRECISION,
    source_row_hash         VARCHAR(128),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT skater_season_stats_valid_scope
        CHECK (
            (stat_scope = 'TEAM' AND team_id IS NOT NULL)
            OR (stat_scope = 'TOTAL' AND team_id IS NULL)
        ),
    CONSTRAINT skater_season_stats_valid_game_type CHECK (game_type IN (2, 3))
);

CREATE UNIQUE INDEX skater_season_stats_grain_idx
    ON skater_season_stats (
        player_id,
        season_start_year,
        COALESCE(team_id, 0),
        stat_scope,
        game_type,
        source_id
    );

CREATE INDEX skater_season_stats_player_history_idx
    ON skater_season_stats (player_id, season_start_year DESC, game_type);

CREATE TABLE goalie_season_stats (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id               BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    season_start_year       SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    team_id                 BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    stat_scope              VARCHAR(8) NOT NULL DEFAULT 'TEAM',
    game_type               SMALLINT NOT NULL,
    source_id               BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    ingestion_run_id        BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    games_played            SMALLINT,
    wins                    SMALLINT,
    losses                  SMALLINT,
    overtime_losses         SMALLINT,
    shots_against           INTEGER,
    saves                   INTEGER,
    save_percentage         DOUBLE PRECISION,
    goals_against           INTEGER,
    goals_against_average   DOUBLE PRECISION,
    shutouts                SMALLINT,
    time_on_ice_seconds     INTEGER,
    source_row_hash         VARCHAR(128),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT goalie_season_stats_valid_scope
        CHECK (
            (stat_scope = 'TEAM' AND team_id IS NOT NULL)
            OR (stat_scope = 'TOTAL' AND team_id IS NULL)
        ),
    CONSTRAINT goalie_season_stats_valid_game_type CHECK (game_type IN (2, 3))
);

CREATE UNIQUE INDEX goalie_season_stats_grain_idx
    ON goalie_season_stats (
        player_id,
        season_start_year,
        COALESCE(team_id, 0),
        stat_scope,
        game_type,
        source_id
    );

CREATE INDEX goalie_season_stats_player_history_idx
    ON goalie_season_stats (player_id, season_start_year DESC, game_type);

CREATE TABLE skater_advanced_season_stats (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id                       BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    season_start_year               SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    team_id                         BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    stat_scope                      VARCHAR(8) NOT NULL DEFAULT 'TEAM',
    game_type                       SMALLINT NOT NULL DEFAULT 2,
    situation                       VARCHAR(24) NOT NULL,
    source_id                       BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    ingestion_run_id                BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    games_played                    SMALLINT,
    ice_time_seconds                DOUBLE PRECISION,
    shifts                          INTEGER,
    game_score                      DOUBLE PRECISION,
    individual_points               SMALLINT,
    individual_goals                SMALLINT,
    individual_primary_assists      SMALLINT,
    individual_secondary_assists    SMALLINT,
    individual_expected_goals       DOUBLE PRECISION,
    individual_shots_on_goal        INTEGER,
    individual_unblocked_attempts   INTEGER,
    on_ice_expected_goals_pct       DOUBLE PRECISION,
    shots_blocked                   INTEGER,
    takeaways                       INTEGER,
    giveaways                       INTEGER,
    penalties                       INTEGER,
    penalties_drawn                 INTEGER,
    offensive_zone_shift_starts     INTEGER,
    defensive_zone_shift_starts     INTEGER,
    neutral_zone_shift_starts       INTEGER,
    extra_metrics                   JSONB NOT NULL DEFAULT '{}'::JSONB,
    source_row_hash                 VARCHAR(128),
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT skater_advanced_stats_valid_scope
        CHECK (
            (stat_scope = 'TEAM' AND team_id IS NOT NULL)
            OR (stat_scope = 'TOTAL' AND team_id IS NULL)
        ),
    CONSTRAINT skater_advanced_stats_valid_game_type CHECK (game_type IN (2, 3))
);

CREATE UNIQUE INDEX skater_advanced_stats_grain_idx
    ON skater_advanced_season_stats (
        player_id,
        season_start_year,
        COALESCE(team_id, 0),
        stat_scope,
        game_type,
        situation,
        source_id
    );

CREATE INDEX skater_advanced_stats_training_idx
    ON skater_advanced_season_stats (season_start_year, situation, player_id);

CREATE TABLE goalie_advanced_season_stats (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id                       BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    season_start_year               SMALLINT NOT NULL REFERENCES seasons(start_year) ON DELETE RESTRICT,
    team_id                         BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    stat_scope                      VARCHAR(8) NOT NULL DEFAULT 'TEAM',
    game_type                       SMALLINT NOT NULL DEFAULT 2,
    situation                       VARCHAR(24) NOT NULL,
    source_id                       BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    ingestion_run_id                BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    games_played                    SMALLINT,
    ice_time_seconds                DOUBLE PRECISION,
    expected_goals_against          DOUBLE PRECISION,
    goals_against                   DOUBLE PRECISION,
    unblocked_shot_attempts         INTEGER,
    blocked_shot_attempts           INTEGER,
    expected_rebounds               DOUBLE PRECISION,
    rebounds                       INTEGER,
    expected_freezes                DOUBLE PRECISION,
    freezes                         INTEGER,
    expected_shots_on_goal          DOUBLE PRECISION,
    shots_on_goal                   INTEGER,
    flurry_adjusted_expected_goals  DOUBLE PRECISION,
    low_danger_shots                INTEGER,
    medium_danger_shots             INTEGER,
    high_danger_shots               INTEGER,
    low_danger_expected_goals       DOUBLE PRECISION,
    medium_danger_expected_goals    DOUBLE PRECISION,
    high_danger_expected_goals      DOUBLE PRECISION,
    low_danger_goals                INTEGER,
    medium_danger_goals             INTEGER,
    high_danger_goals               INTEGER,
    extra_metrics                   JSONB NOT NULL DEFAULT '{}'::JSONB,
    source_row_hash                 VARCHAR(128),
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT goalie_advanced_stats_valid_scope
        CHECK (
            (stat_scope = 'TEAM' AND team_id IS NOT NULL)
            OR (stat_scope = 'TOTAL' AND team_id IS NULL)
        ),
    CONSTRAINT goalie_advanced_stats_valid_game_type CHECK (game_type IN (2, 3))
);

CREATE UNIQUE INDEX goalie_advanced_stats_grain_idx
    ON goalie_advanced_season_stats (
        player_id,
        season_start_year,
        COALESCE(team_id, 0),
        stat_scope,
        game_type,
        situation,
        source_id
    );

CREATE INDEX goalie_advanced_stats_training_idx
    ON goalie_advanced_season_stats (season_start_year, situation, player_id);

CREATE TABLE player_game_stats (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id             BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    player_id           BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    team_id             BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    source_id           BIGINT NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
    ingestion_run_id    BIGINT REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    position_type       VARCHAR(8) NOT NULL,
    time_on_ice_seconds INTEGER,
    goals               SMALLINT,
    assists             SMALLINT,
    points              SMALLINT,
    shots               SMALLINT,
    saves               SMALLINT,
    goals_against       SMALLINT,
    extra_metrics       JSONB NOT NULL DEFAULT '{}'::JSONB,
    source_row_hash     VARCHAR(128),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT player_game_stats_row_key
        UNIQUE (game_id, player_id, team_id, source_id),
    CONSTRAINT player_game_stats_valid_position_type
        CHECK (position_type IN ('skater', 'goalie'))
);

CREATE INDEX player_game_stats_history_idx
    ON player_game_stats (player_id, game_id DESC);

CREATE TABLE model_versions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_type              VARCHAR(32) NOT NULL,
    version                 VARCHAR(64) NOT NULL,
    artifact_uri            TEXT NOT NULL,
    feature_schema          JSONB NOT NULL,
    training_start_season   SMALLINT REFERENCES seasons(start_year) ON DELETE RESTRICT,
    training_end_season     SMALLINT REFERENCES seasons(start_year) ON DELETE RESTRICT,
    evaluation_metrics      JSONB NOT NULL DEFAULT '{}'::JSONB,
    active                  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT model_versions_model_version_key UNIQUE (model_type, version),
    CONSTRAINT model_versions_valid_training_range
        CHECK (
            training_start_season IS NULL
            OR training_end_season IS NULL
            OR training_end_season >= training_start_season
        )
);

CREATE UNIQUE INDEX model_versions_one_active_per_type_idx
    ON model_versions (model_type)
    WHERE active;

CREATE TABLE predictions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version_id            BIGINT NOT NULL REFERENCES model_versions(id) ON DELETE RESTRICT,
    player_id                   BIGINT REFERENCES players(id) ON DELETE SET NULL,
    target_season               SMALLINT REFERENCES seasons(start_year) ON DELETE RESTRICT,
    actual_contract_season_id   BIGINT REFERENCES contract_seasons(id) ON DELETE SET NULL,
    position_group              VARCHAR(16) NOT NULL,
    predicted_aav_cents         BIGINT,
    predicted_cap_percentage    NUMERIC(9, 8),
    input_features              JSONB NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT predictions_valid_position_group
        CHECK (position_group IN ('forward', 'defense', 'goalie')),
    CONSTRAINT predictions_nonnegative_aav
        CHECK (predicted_aav_cents IS NULL OR predicted_aav_cents >= 0),
    CONSTRAINT predictions_nonnegative_cap_percentage
        CHECK (predicted_cap_percentage IS NULL OR predicted_cap_percentage >= 0)
);

CREATE INDEX predictions_player_history_idx
    ON predictions (player_id, created_at DESC);

CREATE INDEX predictions_model_idx
    ON predictions (model_version_id, created_at DESC);

COMMIT;
